Repository metersphere/metersphere, pull requests merged in 2022-07, with the labels that each got.

#15447 docs: 更新在线体验宣传语
  README.md
Labels: dev

#15588 docs: 在issue模板中增加升级v1.20提示
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/feature.yml
Labels: dev

#15988 fix(测试跟踪): 修复导入的JMX文件失败重试不生效问题
  backend/src/main/java/io/metersphere/api/exec/api/ApiCaseSerialService.java
Labels: approved, dev

#16353 docs: 修改 Readme 中快速安装命令
  README.md
Labels: lgtm, dev
