Repository metersphere/metersphere, pull requests merged in 2022-04, with the labels that each got.

#12239 docs: 更新安全说明联系邮箱
  SECURITY.md
Labels: approved

#12240 docs: 使用表单模式的issue模板
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/feature.yml
  .github/ISSUE_TEMPLATE/question.md
  .github/ISSUE_TEMPLATE/question.yml
Labels: lgtm

#12265 fix(接口测试): 缺陷管理-jira缺陷往ms同步，图片不显示
  backend/src/main/java/io/metersphere/track/issue/JiraPlatform.java
  backend/src/main/java/io/metersphere/track/issue/client/BaseClient.java
  backend/src/main/java/io/metersphere/track/issue/client/JiraAbstractClient.java
Labels: approved

#12389 fix(接口测试): 第三方平台 禅道 & azure devops 缺陷同步问题
  backend/src/main/java/io/metersphere/commons/utils/FileUtils.java
  backend/src/main/java/io/metersphere/track/issue/AbstractIssuePlatform.java
  backend/src/main/java/io/metersphere/track/issue/ZentaoPlatform.java
  backend/src/main/java/io/metersphere/track/issue/client/ZentaoClient.java
  backend/src/main/java/io/metersphere/track/issue/domain/azure/AzureDevopsWorkItemsBatchResponse.java
  backend/src/main/java/io/metersphere/track/service/TestCaseService.java
  frontend/src/business/components/track/plan/view/comonents/functional/FunctionalTestCaseEdit.vue
Labels: approved

#12459 build: 修改构建容器action中的触发分支
  .github/workflows/build-push.yml
Labels: lgtm

#12476 build: 增加不包含xpack的构建action
  .github/workflows/build-push-oss.yml
Labels: approved, lgtm

#12576 fix(接口测试): tfs平台缺陷模板添加自定义字段 同步问题处理
  backend/src/main/java/io/metersphere/track/issue/domain/azure/AzureDevopsWorkItemsBatchResponse.java
Labels: lgtm

#12581 fix(接口测试): tfs平台缺陷模板添加自定义字段 同步问题处理
  backend/src/main/java/io/metersphere/track/issue/domain/azure/AzureDevopsWorkItemsBatchResponse.java
Labels: approved, lgtm

#12588 fix(接口测试): tfs平台缺陷模板添加自定义字段 同步问题处理
  backend/src/main/java/io/metersphere/track/issue/domain/azure/AzureDevopsWorkItemsBatchResponse.java
Labels: approved, lgtm, v1.20

#12627 Update bug.yml
  .github/ISSUE_TEMPLATE/bug.yml
Labels: lgtm, dev

#12660 build: dev分支触发构建action
  .github/workflows/build-push.yml
Labels: approved, lgtm, dev

#12727 refactor(测试跟踪): 关联缺陷界面增加搜索功能
  frontend/src/business/components/track/case/components/IssueRelateList.vue
Labels: approved, lgtm

#12792 fix(接口测试): 禅道pro版缺陷同步图片路径错误问题
  backend/src/main/java/io/metersphere/track/issue/client/ZentaoClient.java
Labels: approved, lgtm

#12795 fix(接口测试): 禅道pro版缺陷同步图片路径错误问题
  backend/src/main/java/io/metersphere/track/issue/client/ZentaoClient.java
Labels: approved

#12981 docs: 增加徽章
  README.md
Labels: approved, lgtm

#13009 build: 使用不同的action处理push及pr
  .github/workflows/add-labels-for-pr.yml
  .github/workflows/create-pr-from-push.yml
Labels: approved, lgtm, dev

#13180 docs: 更新readme
  README.md
Labels: approved, lgtm, dev

#13188 build: 为action声明permissions
  .github/workflows/add-labels-for-pr.yml
Labels: approved, lgtm, dev
